openapi: 3.0.1
info:
  title: Spring Boot API
  version: 1.0
paths:
  /api/login/authenticate:
    post:
      summary: Authenticate user
      responses:
        '200':
          description: JWT Token
  /api/bookings:
    get:
      summary: Get all bookings
      responses:
        '200':
          description: List of bookings
